### ISSUE TITLE
bam_cigar2rlen

### ISSUE THREAD

**Issue by mweberr** [brentp/cigar#4]
Hi,
I just found your efficient library to process CIGAR Strings into Python Lists.
Do you know a Python-way to calculate the **rlen** attribute, which is internally computed by samtools in Code ?

hts_pos_t bam_cigar2rlen(int n_cigar, const uint32_t *cigar)
{
    int k;
    hts_pos_t l;
    for (k = l = 0; k < n_cigar; ++k)
        if (bam_cigar_type(bam_cigar_op(cigar[k]))&2)
            l += bam_cigar_oplen(cigar[k]);
    return l;
}

My first try is :
```{python}
c=Cigar('20M5I10M3I5M')
sum([x[0] for x in c.items() if x[1] == "M" ])
```

**Comment by brentp** [comment]
Hi, I don't recommend using this library. Maybe you can use pysam to do this.

**Comment by mweberr** [comment]
Thanks! I just learned that library pysam exists. :)
